title: Woojong Koh
author: Woojong Koh
description: Founder of Cowork AI
github_username: wjkoh
theme: jekyll-theme-slate
collections:
  - authors
plugins:
  - jekyll-sitemap
url: "https://wjkoh.com"
