baseURL = "https://wjkoh.com/"
languageCode = "en-us"
title = "Woojong Koh"
theme = "typo"

[pagination]
  pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Woojong Koh"
  description = "CEO & Founder of Cowork AI. Software Engineer and Researcher."
  showSummary = true
  showTags = true
  
  homeCollection = "posts"
  homeCollectionTitle = "Latest"
  paginationSize = 5

  [[params.social]]
    name = "github"
    url = "https://github.com/wjkoh"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/wjkoh"
  [[params.social]]
    name = "email"
    url = "mailto:wjkoh@cwrk.ai"

  [[params.menu]]
    name = "about"
    url = "/"
  [[params.menu]]
    name = "posts"
    url = "/posts/"
  [[params.menu]]
    name = "resume"
    url = "/assets/woojong-koh-resume.pdf"
    newTab = true
